[package]
name = "wgpucraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"

winit = { version = "0.29.8", features = ["rwh_05"]}

